import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  imageUrl: 'https://i.imgur.com/UYUPjdt.png',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:image" content={metadata.imageUrl} />
        <meta property="og:type" content="website" />
        <link rel="icon" href='https://i.imgur.com/QtTnpkw.png' />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}